/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation
 The sidebars can be generated from the filesystem, or explicitly defined here.
 Create as many sidebars as you want.
 */

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
    "quick-start",
    {
      type: "category",
      label: "💡 Demos",
      link: {
        type: "generated-index",
        title: "💡 Showcases of the library",
        slug: "/demo",
      },
      items: [
        {
          type: "category",
          label: "🔎 Specifications",
          link: {
            type: "generated-index",
            title: "🔎 Specifications showcases",
            slug: "/demo/specs",
          },
          items: [
            {
              type: "autogenerated",
              dirName: "specs",
            },
          ],
        },
        {
          type: "category",
          label: "🛠️ Customizations",
          link: {
            type: "generated-index",
            title: "🛠️ Customizations showcases",
            slug: "/demo/custom",
          },
          items: [
            {
              type: "autogenerated",
              dirName: "custom",
            },
          ],
        },
        {
          type: "category",
          label: "🗺️ Real word examples",
          link: {
            type: "generated-index",
            title: "🗺️ Real word examples",
            slug: "/demo/examples",
          },
          items: [
            {
              type: "link",
              label: "⌚ Timing",
              href: "/examples/timing",
            },
          ],
        },
      ],
    },
    "contributing",
    {
      type: "link",
      label: "📖 API Reference",
      href: "/api",
    },
    "faq",
    "next-steps",
  ],
};
