name: Package Size Report

on:
  pull_request:
    branches: [main]

permissions:
  pull-requests: write

jobs:
  pkg-size-report:
    name: Package Size Report
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.3

      - name: Setup Node.js
        uses: actions/setup-node@v4.4.0
        with:
          node-version: "lts/*"

      - name: Package size report
        uses: pkg-size/action@v1.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          hide-files: "*.{js,css}.map"
